### ISSUE TITLE
How to get this going?

### ISSUE THREAD

**Issue by heyklaus** [stephenkirk/vkeys-to-json#1]
Hello @stephenkirk , thank you for your work here. I'm not a programmer so sorry for my question ... but what exactly do I have to do with the .sh file? And am I right in presuming that it will convert the .vkeys files into (editable) .keysjson files? It would be great to get some advice here ... Best, Klaus

**Comment by stephenkirk** [comment]
Hey Klaus,

I've only tested this on a Mac. However, you should be able to do this on any OS that supports Openssl.

On Mac (and presumably, any Unix environment), you would use this by running this in the project root:
1. Making `decrypt.sh` executable: `chmod +x ./decrypt.sh`
2. Running `decrypt.sh` on your .vkeys file: `decrypt.sh NAME_OF_VKEYS_FILE.vkeys`

If you run Windows, I could see you getting this working in two ways:
A. Using Windows Subsystem for Linux, set up a linux environment and then follow the above instructions:
https://docs.microsoft.com/en-us/windows/wsl/install-win10

B. Download openssl for Windows, and then running the following (untested) command in a command prompt:
`openssl enc -aes-128-cbc -d -in NAME_OF_VKEYS_FILE.vkeys -out output.keysjson -K 344e6675726239344236695736345144 -iv 0`

Stephen

**Comment by heyklaus** [comment]
Hi Stephen, thank you very much for your quick reply. I'm on a Mac (should have told you so), and it works perfectly! The file itself looks a bit convoluted in my editor (Brackets), no line breaks there. But I'll work it out ... Thanks again, helps a lot!

**Comment by stephenkirk** [comment]
Very glad to hear, Klaus!
I'll make sure to update the readme with the above instructions.
